apiVersion: v1
kind: Service
metadata:
  name: flask-app
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-internal: "false"
   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-app