apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask-app


  #   helm install aws-load-balancer-controller eks/aws-load-balancer-controller 
  # -n kube-system 
  # --set clusterName=khainheks 
  # --set serviceAccount.create=false 
  # --set serviceAccount.name=aws-load-balancer-controller 
  # --set region=ap-southeast-1 
  # --set vpcId=vpc-036cd2fc7e7000ab6