---
apiVersion: v1
kind: Namespace
metadata:
  name: vti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vti
  name: deployment-vti
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vti-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vti-app
    spec:
      containers:
      - image: khainh3101/vti-final-exam:latest
        imagePullPolicy: Always
        name: vti-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: vti
  name: service-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: vti-app